### ISSUE TITLE
dropdown-submenu

### ISSUE THREAD

**Issue by Legin76** [CWSpear/bootstrap-hover-dropdown#74]
Although no longer officially included in bootstrap 3 dropdown-submenu still works and just requires a few lines of css. 

I've been trying to use with this script which pauses it perfectly but clicking on any links on the menu does not work. 

I've tested it with the demo by un-commenting the submenu code and adding the css below and had the exact same issue.

``` css
.dropdown-submenu {
    position: relative;
}
.dropdown-submenu>a.submenu:focus {
    background-color: rgba(255, 255, 255, .30);
}
.dropdown-submenu>a.submenu:hover {
    background-color: rgba(255, 255, 255, .30);
}
.dropdown-submenu>.dropdown-menu {
    top: 0;
    left: 100%;
    padding-top: 0;
    margin-top: 0px;
    margin-left: 0px;
    -webkit-border-radius: 0 0 0 0;
    -moz-border-radius: 0 0 0;
    border-radius: 0 0 0 0;
}

.dropdown-submenu:hover>.dropdown-menu {
    display: block;
}

.dropdown-submenu .dropdown-menu a {
    max-width: 220px;
    display: block;
    white-space: normal;
}

.dropdown-submenu>a:after {
    display: block;
    content: " ";
    float: right;
    height: 0;
    border-color: transparent;
    border-style: solid;
    border-width: 5px 0 5px 5px;
    border-left-color: #ccc;
    margin-top: 5px;
    margin-right: -6px;
}

.dropdown-submenu:hover>a:after {
    border-left-color: #fff;
}

.dropdown-submenu.pull-left {
    float: none;
}

.dropdown-submenu.pull-left>.dropdown-menu {
    left: -100%;
    margin-left: 10px;
    -webkit-border-radius: 0 0 0 0;
    -moz-border-radius: 0 0 0 0;
    border-radius: 0 0 0 0;
}
```
