### ISSUE TITLE
add animate in hover

### ISSUE THREAD

**Issue by ericfpavoni** [CWSpear/bootstrap-hover-dropdown#94]
How do can i  add class for animate submenu in hover. me mean is when i hover link submenu show with any css animate class like this :

``` css
.animated {
        -webkit-animation-duration: 1s;
        animation-duration: 1s;
        -webkit-animation-fill-mode: both;
        animation-fill-mode: both;
    }
    @-webkit-keyframes bounceIn {
        0% {
            opacity: 0;
            -webkit-transform: scale(.3);
        }
        50% {
            opacity: 1;
            -webkit-transform: scale(1.05);
        }
        70% {
            -webkit-transform: scale(.9);
        }
        100% {
            -webkit-transform: scale(1);
        }
    }
    @keyframes bounceIn {
        0% {
            opacity: 0;
            transform: scale(.3);
        }
        50% {
            opacity: 1;
            transform: scale(1.05);
        }
        70% {
            transform: scale(.9);
        }
        100% {
            transform: scale(1);
        }
    }
    .bounceIn {
        -webkit-animation-name: bounceIn;
        animation-name: bounceIn;
    }
```

thanks for your time
